plan_meals:
  description: >
    Input is a simple inspiration text with food preferences or requests.
    Examples: "Want to eat noodles?", "Want one meal to eat fish?", "Want a tomato and eggs? Less sugar, less sauce."
    Create today's meal plan (Breakfast, Lunch, Dinner; optional Snack).
    Rules: balanced, low oil/salt; reuse ingredients; respect preferences mentioned in inspiration;
    assume pantry staples (salt, sugar, soy sauce, vinegar, pepper, oil).

    IMPORTANT: Output should be a well-structured README file with nice formatting.
    Use proper Markdown formatting with headers, lists, and clear structure.
    Return in EXACTLY this format:

    # Today's Meal Plan

    **Breakfast: <meal_name>**

    - <item qty, ...>

    **Lunch: <meal_name>**

    - <item qty, ...>

    **Dinner: <meal_name>**

    - <item qty, ...>

    **Snack: <snack_name>**

    - <item qty, ...>

    <End of meal plan>

  expected_output: "Well-structured README file with proper Markdown formatting for today's meal plan."
  agent: recipe_planner
  inputs:
    inspiration: "${inspiration}"

build_grocery_list:
  description: >
    Read today's meal plan text from plan_meals and build a shopping list.
    Group items by: Proteins / Staples / Vegetables / Fruits / Dairy / Other.
    Provide easy buy sizes
    (e.g., 'chicken breast ~400g (2 pieces)'); note optional/swappable items.
    Exclude pantry staples (salt, sugar, soy sauce, vinegar, pepper, oil).

    IMPORTANT: Output should be a well-structured README file with nice formatting.
    Use proper Markdown formatting with headers, lists, and clear structure.
    Return in EXACTLY this format:

    # Grocery Shopping List

    ## Proteins
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Staples
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Vegetables
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Fruits
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Dairy
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Other
    - **<item>**: <total/size>
    - **<item>**: <total/size>

    ## Notes
    - Pantry staples not included (salt, sugar, soy sauce, vinegar, pepper, oil)
    - Mention any simple swaps (e.g., banana → berries)
    - Items marked with * are optional or swappable

  expected_output: "Well-structured README file with proper Markdown formatting for grocery shopping list."
  agent: grocery_list_builder
  depends_on:
    - plan_meals
  inputs:
    meal_plan: "${tasks.plan_meals.output}"
